#!/bin/sh

print_usage() {
    echo "usage: viv [--scroll n] file/directory"
    echo ""
    echo "View file/directory in your browser with Vivify."
    echo ""
    echo "options:"
    echo "  --help              show this help message and exit"
    echo "  --version           show version information"
    echo "  -s n, --scroll n    for markdown files, scroll so that content at source line n is visible"
}

if [ "$#" -lt 1 -o "$1" = "-h" -o "$1" = "--help" ]; then
    print_usage
    exit 1
fi

output=`mktemp`
cleanup() {
    rm -f "$output"
}
trap cleanup EXIT

nohup vivify-server $@ > "$output" 2> /dev/null &

# print stdout of vivify-server until STARTUP COMPLETE is found
tail -f "$output" | while read line; do
    if echo "$line" | grep -q "STARTUP COMPLETE"; then
        pkill -P $$ tail
        break
    fi
    echo "$line"
done
